### ISSUE TITLE
What parts of the new WDTK theme should we port into alavetelitheme?

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/alavetelitheme#48]

**Comment by garethrees** [comment]
IMO

- Banner tidying
- Locale switcher
- Hero
- The nicer bodies/request listing on the homepage
- the footer
- The nicer request page sidebar
- the better print stylesheets (when merged)
- probably the button styles

I think it might be easier to think about what _not_ to port over…

- mySociety bar
- 1-2-3 section (not sure how well that would apply to all installs)
- colours

**Comment by garethrees** [comment]
Thing | Alavetelitheme | Core | Notes
------|----------------|------|------
[Printed from](http://git.io/vqPev) | - | Markup and CSS | |
[Logo](http://git.io/vqPvf) | Pretty CSS | Markup, basic CSS to position | |
[Locale Switcher](http://git.io/vqPfw) | JS + CSS | Markup, Style it in the way it looks now (inline list | Would be nice to extract logic to controller / helpers |
[Nav](http://git.io/vqPn2) | CSS | - | |
[Logged in](http://git.io/vqPnf) | CSS | - |Also http://git.io/vqPnH |
[Hero](http://git.io/vqPUe) | Pretty CSS | Markup, basic CSS | |
[How it Works](http://git.io/vqPUE) | Pretty CSS | Markup, basic CSS | I'm not _that_ sure on this one. Will it apply to all installs? |
[Bodies List](http://git.io/vqPTB) | Pretty CSS | Markup, basic CSS | Minor code refactoring |
[Requests List](http://git.io/vqPTK) | Pretty CSS | Markup, basic CSS | Minor code refactoring |
[Footer](http://git.io/vqPkB) | Pretty CSS | Markup, basic CSS | Remove UK specific stuff, needs facebook url config |
Buttons | Pretty CSS | - | |
[Button hierarchy](http://git.io/vqPGY) | CSS | Markup | e.g. add `.button-secondary` with no styles |
Fonts | Yes | - | |
[Pagination](http://git.io/vqPsy) | Yes | - | |
Print Stylesheets | | | ? |
[Icons](http://git.io/vqPsr) | - | Yes | |
[Blog](http://git.io/vqPGr) | CSS | - | **check what it looks like on core** |
[Help Pages](http://git.io/vqPZn) | | | I think this is already available in core – might be able to remove from WDTK |
[Sidebars](http://git.io/vqPZQ) | CSS | - | |

**Comment by wrightmartin** [comment]
> [How it works] I'm not that sure on this one. Will it apply to all installs?

It's quite specific to WDTK, even the three steps might be hard to lift and shift to a new country. Shall we leave it?

**Comment by garethrees** [comment]
[Lots](http://tuderechoasaber.es/) [of](http://www.quesabes.org/) [sites](https://chiedi.dirittodisapere.it/) do like the 1,2,3 though

**Comment by garethrees** [comment]
All the checkboxes are ticked, so I think this is done! :tada: :tada: :zap:
