### ISSUE TITLE
Mobile nav menu cannot be closed once it is opened

### ISSUE THREAD

**Issue by zarino** [mysociety/alavetelitheme#66]
![sort](https://cloud.githubusercontent.com/assets/739624/10690807/424e6fe6-797c-11e5-96b2-e06d7ba87bde.gif)

Looking at the page source, I think it might be a CSS specificity issue, where the proper behaviour (eg: `display: none` for `a.open` when the menu is open) is getting overridden by a *slightly* more specific selector from somewhere else. And likewise, the `.close` button is affected by the same bug.

![screen shot 2015-10-23 at 11 51 27](https://cloud.githubusercontent.com/assets/739624/10690845/8917f8d4-797c-11e5-82b0-b61697a8d8c2.png)

**Comment by lizconlan** [comment]
this seems to stem from a problem in alaveteli core, closing in favour of https://github.com/mysociety/alaveteli/issues/2870
