### ISSUE TITLE
Request status text is the same colour as the background

### ISSUE THREAD

**Issue by garethrees** [mysociety/alavetelitheme#83]
![screen shot 2016-11-25 at 12 00 50](https://cloud.githubusercontent.com/assets/282788/20624941/d515f00e-b307-11e6-8578-352cf9189d98.png)

![screen shot 2016-11-25 at 12 00 57](https://cloud.githubusercontent.com/assets/282788/20624946/d8095c42-b307-11e6-9472-da59cbf8810e.png)

**Comment by garethrees** [comment]
Fixed in wdtk by doing https://github.com/mysociety/whatdotheyknow-theme/commit/77d1789d605088c6769ac2c93492d15967c344b7

**Comment by garethrees** [comment]
This gets fixed by https://github.com/mysociety/alaveteli/pull/3639

**Comment by lizconlan** [comment]
We might need to change the the text colour in the theme(s), either to black/dark-grey or a darker shade of the status colour as this is a) a bit blurry for me and b) doesn't pass contrast ratio accessibility guidelines (colour refs - text `#62b356`, background `#d0e8cc`)

![screen shot 2016-12-06 at 15 31 22](https://cloud.githubusercontent.com/assets/27760/20931648/ac21c1a8-bbc9-11e6-8b8b-2c21b1b94d7a.png)

**Comment by garethrees** [comment]
I didn't find the green/red too bad, but the yellow was a little difficult on one of my monitors. I think making the text black (as it is in core) is the best option. Alternatively, a _very_ darkened version of the colour? @wrightmartin any thoughts?

**Comment by lizconlan** [comment]
Not enough contrast between the 2 greens to satisfy the contrast test (hence blurry for me), I found the slight tweak to mix some more white (75 rather than 70%) in to the background was enough for my eyes to parse it as text rather than texture without wrecking the intended effect but I'm not convinced that's enough. Happy to bow to someone who knows what they're talking about tho  👓

**Comment by lizconlan** [comment]
Also unconvinced that "bit weird for me" is a compelling reason to change __anything__ other than my monitor settings

**Comment by wrightmartin** [comment]
Happy with the core style black (`#333333`) on green
