### ISSUE TITLE
AssetNotPrecompiled exception

### ISSUE THREAD

**Issue by zarino** [mysociety/alavetelitheme#98]
![screen shot 2017-09-12 at 15 35 40](https://user-images.githubusercontent.com/739624/30331560-15e0ee7e-97d0-11e7-9e1c-5e3761938793.png)

```
Sprockets::Rails::Helper::AssetNotPrecompiled in RequestController#show

Asset was not declared to be precompiled in production. Add
`Rails.application.config.assets.precompile += %w( logo-opengraph.png )` 
to `config/initializers/assets.rb` and restart your server
```

When loading any page under https://github.com/mysociety/alavetelitheme/commit/0dee8c3bd06dd8779500667018185fab6dcee04e on https://github.com/mysociety/alaveteli/commit/c8f2707ef4b46d9b6ba73034dd9dc91ec0f91b88.

**Comment by zarino** [comment]
@garethrees says you probably need to replicate this commit from whatdotheyknow-theme, in alavetelitheme: https://github.com/mysociety/whatdotheyknow-theme/commit/f99f7fd4538e57c2429ee2301317785c76eb08b0

**Comment by garethrees** [comment]
Linking to https://github.com/mysociety/alaveteli/issues/3804

**Comment by garethrees** [comment]
This got fixed by https://github.com/mysociety/alavetelitheme/pull/99
